version: '3.6'
services:
  mysql:
    image: mysql:5.7
    container_name: rookie-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "rd3"
      MYSQL_PASSWORD: "asd123"
      MYSQL_ROOT_PASSWORD: "asd123"
    volumes:
      - /var/log/docker/data/mysql:/var/lib/mysql
    networks:
      - rookie-mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: rookie-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: rookie-mysql
    networks:
      - rookie-mysql
  redis:
    image: redis:3.0.0
    container_name: rookie-redis
    stdin_open: true
    tty: true
    ports:
      - 6379:6379
    volumes:
      - /Users/po_lee/Desktop/workspace/docker/rookie/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "sh", "-c", "redis-server", "/usr/local/etc/redis/redis.conf" ]  # 容器啟動後執行的命令
    networks:
      - rookie-mysql
  rookie:
    build:
      context: .
      dockerfile: basicDocker
    image: rookie:1.0.1
    container_name: rookie_compose
    stdin_open: true
    tty: true
    ports:
      - "8000:80"
    volumes:
      - /Users/po_lee/Desktop/workspace/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/po_lee/Desktop/workspace/rookie_training:/var/www/html/rookie
    command: ["sh","-c","php-fpm7 -R;nginx"]
    networks:
      - rookie-mysql
networks:
  rookie-mysql:

