apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-pod
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service-2
spec:
  type: NodePort
  selector:
    app: my-pod-2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    
