version: '3.6'
services:
  finaltest:
    build:
      context: .
      dockerfile: basicDocker 
    image: finaltest:1.0.1
    container_name: finaltest
    ports:
      - 10081:80
    volumes:
      - /Users/po_lee/Desktop/workspace/casino_member:/home/gbt/casino_member
      - /Users/po_lee/Desktop/workspace/casino/general:/home/gbt/general
      - /Users/po_lee/Desktop/workspace/docker/finaltest/config_env.php
      - /Users/po_lee/Desktop/workspace/docker/finaltest/config_env.php:/home/gbt/casino_member/config/config_env.php
      - /Users/po_lee/Desktop/workspace/docker/finaltest/config_inc.php:/home/gbt/casino_member/config/config_inc.php
      - /Users/po_lee/Desktop/workspace/docker/finaltest/nginx.conf:/etc/nginx/nginx.conf
      # - /Users/po_lee/Desktop/workspace/rookie_training/log:/var/log
      # - /Users/po_lee/Desktop/workspace/rookie_training/txt:/home/gbt/txt
    command: [ "sh", "-c", "php-fpm7 -R;nginx;" ]    # 容器啟動後執行的命令
    networks:
      - final-test
  finaltest-casino:
    build:
      context: .
      dockerfile: CasinoDockerfile
    image: casinobase 
    ports:
      - "10082:80"
    container_name: finaltest-casino
    volumes:
      - /Users/po_lee/Desktop/workspace/casino/casino:/home/gbt/casino/
      - /Users/po_lee/Desktop/workspace/casino/general:/home/gbt/general/
      - /Users/po_lee/Desktop/workspace/casino/config/dev/casino/DockerCompose/DockerConfig:/home/gbt/casino/config/
      - /Users/po_lee/Desktop/workspace/casino/game:/home/gbt/game/
      - /Users/po_lee/Desktop/workspace/casino/config/dev/casino/DockerCompose/casinonginx.conf:/etc/nginx/nginx.conf
    command: [ "sh", "-c", "php-fpm7 -R; nginx;" ]
networks:
    final-test:
